services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ASD123as  
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
